mqtt:
  host: localhost
  port: 1883
  topic_prefix: bt-mqtt-gateway
  client_id: bt-mqtt-gateway
  availability_topic: availability

manager:
  command_timeout: 30
  workers:
    ruuvitag:
      args:
        devices:
          tag1: FB:EB:26:77:1A:A8
          tag2: F5:61:1D:1D:50:1C
          tag3: CD:2C:43:AB:B2:27
        topic_prefix: ruuvitag
      update_interval: 1
